name: Release
on:
  push:
    branches:
      - main

env:
  THIRD_PARTY_GIT_AUTHOR_EMAIL: opensource+bot@newrelic.com
  THIRD_PARTY_GIT_AUTHOR_NAME: nr-opensource-bot

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Add plugins for semantic release
        run: npm install @semantic-release/git @semantic-release/changelog @semantic-release/github

      - name: Run semantic-release
        env:
          # Use nr-opensource-bot for authoring commits done by
          # semantic-release (rather than using @semantic-release-bot)
          GIT_AUTHOR_NAME: "nr-opensource-bot"
          GIT_AUTHOR_EMAIL: "opensource+bot@newrelic.com"
          GIT_COMMITTER_NAME: "nr-opensource-bot"
          GIT_COMMITTER_EMAIL: "opensource+bot@newrelic.com"
          GITHUB_TOKEN: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
        run: npx semantic-release
